### ISSUE TITLE
Getting "_pickle.UnpicklingError: invalid load key, '\xff'." when trying to invert

### ISSUE THREAD

**Issue by rshaw5** [hlky/sd-enable-textual-inversion#3]
# Steps to reproduce
- Set up a clean environment following https://rentry.org/GUItard
- Clone this repo and copy it into the main repo per readme
- Overwrite existing directories when doing the above move
- Start up the gui
- Upload an image into the inverter box
- Hit generate
- See following error and traceback in anaconda terminal

```
Traceback (most recent call last):
  File "C:\Users\Rob\anaconda3\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\Rob\anaconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Users\Rob\anaconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Rob\anaconda3\envs\ldo\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Rob\anaconda3\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Rob\anaconda3\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 611, in txt2img
    output_images, seed, info, stats = process_images(
  File "scripts/webui.py", line 424, in process_images
    load_embeddings(fp)
  File "scripts/webui.py", line 250, in load_embeddings
    model.embedding_manager.load(fp.name)
  File "f:\sd-gui\ldm\modules\embedding_manager.py", line 136, in load
    ckpt = torch.load(ckpt_path, map_location='cpu')
  File "C:\Users\Rob\anaconda3\envs\ldo\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\Rob\anaconda3\envs\ldo\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\xff'.
```

**Comment by rshaw5** [comment]
I work in PHP and JS during the day, so I have some idea how Python works, but not enough to decode this error. I don't think this is user error because I uninstalled and reinstalled everything cleanly per the docs. Any thoughts?

**Comment by hlky** [comment]
> Upload an image into the inverter box

That's not how it works

[textual-inversion](https://textual-inversion.github.io/)

You need to train embeddings then use the embedding file

For training see:
[rinongal/textual_inversion](https://github.com/rinongal/textual_inversion)
[nicolai256/Stable-textual-inversion_win](https://github.com/nicolai256/Stable-textual-inversion_win)

Please note: training uses a HUGE amount of vram, you will struggle to get it working on <12gb vram, I have but only by changing the size: 512 to size: 448 in this section of v1-finetune or lowmemory version: 
```
data:
  target: main.DataModuleFromConfig
```

Alternatively you can test with an embedding from [here](https://github.com/hlky/sd-embeddings)
There are 2 available atm, see the readme.md of each one for more info i.e. amount of images in training dataset, steps trained

You use * in the prompt where you want the custom trained thing. Note: requires PHD in prompt crafting and messing around with sampler, steps, cfg, the prompt itself, to get anything resembling a good result (possibly caused by rubbish images used for training as well)
